import { FormEvent, useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { api, Project, PushDeployment, values, Version } from "./api";
import { Dashboard } from "./Dashboard";
import "../../internal/api/web/style.css";

type Tab = "versions" | "push" | "logs" | "preview" | "team" | "deploy" | "diff";
type GlobalView = "workspace" | "dashboard";
const projectTabs: readonly [Tab, string][] = [["versions", "版本管理"], ["push", "发布到远程"], ["logs", "发布日志"], ["preview", "拉取预览"], ["team", "团队"], ["deploy", "部署"], ["diff", "差异"]];

function App() {
  const [me, setMe] = useState<{ username: string; is_admin: boolean } | null>(null);
  const [projects, setProjects] = useState<Project[]>([]); const [project, setProject] = useState<Project | null>(null);
  const [versions, setVersions] = useState<Version[]>([]); const [tab, setTab] = useState<Tab>("versions"); const [message, setMessage] = useState("");
  const [view, setView] = useState<GlobalView>("workspace");
  const loadProjects = async () => { const list = (await api<Project[] | null>("/projects")) ?? []; setProjects(list); setProject((now) => list.find((item) => item.id === now?.id) ?? list[0] ?? null); };
  const loadVersions = async () => { if (project) setVersions((await api<Version[] | null>(`/projects/${project.id}/versions`)) ?? []); };
  useEffect(() => { api<{ username: string; is_admin: boolean }>("/me").then((user) => { setMe(user); return loadProjects(); }).catch(() => setMe(null)); }, []);
  useEffect(() => { void loadVersions(); }, [project?.id]);
  useEffect(() => { document.title = me ? "express233 · 发布控制台" : "express233 · 登录"; }, [me]);
  if (!me) return <Login onLogin={async (user) => { setMe(user); await loadProjects(); }} />;
  const selectProject = (next: Project) => { setProject(next); setView("workspace"); };
  return <div className="app-shell" data-testid="app-shell"><Sidebar projects={projects} selected={project} onSelect={selectProject} onCreated={loadProjects} username={me.username} view={view} onView={setView}/><main className="main">{view === "dashboard" ? <Dashboard projects={projects}/> : <><header className="workspace-header"><div className="workspace-title"><h1 data-testid="cur-project">{project?.name ?? "选择项目"}</h1></div>{project && <nav className="project-tabs" role="tablist">{projectTabs.map(([id, label]) => <button type="button" key={id} className={`project-tab ${tab === id ? "active" : ""}`} onClick={() => setTab(id)}>{label}</button>)}</nav>}</header>{message && <div className="toast ok">{message}</div>}{project ? <Workspace project={project} versions={versions} tab={tab} onMessage={setMessage} reloadVersions={loadVersions}/> : <div className="empty-state"><h2>选择项目</h2><p>在左侧选择或创建项目，管理版本包与 server_id 配置替换。</p></div>}</>}</main></div>;
}

function Login({ onLogin }: { onLogin: (user: { username: string; is_admin: boolean }) => Promise<void> }) { const [error, setError] = useState(""); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { const user = await api<{ username: string; is_admin: boolean; token?: string }>("/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ username: data.get("username"), password: data.get("password") }) }); if (user.token) localStorage.setItem("express233_jwt", user.token); await onLogin(user); } catch (err) { setError((err as Error).message); } } return <div className="login-screen" data-testid="login-panel"><form className="login-card" onSubmit={submit}><div className="login-brand"><h1>express233</h1><p className="login-sub">游戏逻辑服 · 拉模式部署中央控制台</p></div><label className="field"><span>用户名</span><input className="input" name="username" defaultValue="root" autoComplete="username"/></label><label className="field"><span>密码</span><input className="input" name="password" type="password" autoComplete="current-password"/></label><button className="btn btn-primary btn-block" data-testid="login-submit">登录</button>{error && <p className="err">{error}</p>}</form></div> }

function Sidebar({ projects, selected, onSelect, onCreated, username, view, onView }: { projects: Project[]; selected: Project | null; onSelect: (project: Project) => void; onCreated: () => Promise<void>; username: string; view: GlobalView; onView: (view: GlobalView) => void }) { const [name, setName] = useState(""); async function create() { if (!name.trim()) return; await api("/projects", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name }) }); setName(""); await onCreated(); } return <aside className="sidebar"><div className="sidebar-brand-row"><span className="brand-name">express233</span></div><div className="sidebar-section"><div className="section-label">项目</div><div className="new-project-row"><input className="input input-sm" value={name} onChange={(event) => setName(event.target.value)} placeholder="新项目名称" data-testid="new-project-input"/><button className="btn btn-primary btn-sm" onClick={create} data-testid="add-project" aria-label="新建项目">+</button></div></div><ul className="project-list" data-testid="project-list">{projects.map((item) => <li key={item.id} className={`project-item ${item.id === selected?.id && view === "workspace" ? "selected" : ""}`} onClick={() => onSelect(item)} title={item.name}><svg className="project-item-icon" aria-hidden="true" viewBox="0 0 24 24"><path d="M3 7a2 2 0 0 1 2-2h5l2 2h7a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7Z"/></svg><span className="project-item-name">{item.name}</span></li>)}</ul><nav className="sidebar-nav"><div className="section-label">导航</div><button type="button" className={`sidebar-nav-item ${view === "workspace" ? "active" : ""}`} onClick={() => onView("workspace")}><svg className="nav-svg" aria-hidden="true" viewBox="0 0 24 24"><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></svg><span>工作区</span></button><button type="button" className={`sidebar-nav-item ${view === "dashboard" ? "active" : ""}`} onClick={() => onView("dashboard")} data-testid="nav-dashboard"><svg className="nav-svg" aria-hidden="true" viewBox="0 0 24 24"><path d="M4 19V9M10 19V5M16 19v-7M22 19V2"/><path d="M2 19h22"/></svg><span>数据大盘</span></button></nav><div className="sidebar-footer"><span className="user-label" data-testid="whoami">{username}</span></div></aside> }

function Workspace({ project, versions, tab, onMessage, reloadVersions }: { project: Project; versions: Version[]; tab: Tab; onMessage: (value: string) => void; reloadVersions: () => Promise<void> }) { if (tab === "push") return <PushTab project={project} versions={versions} onMessage={onMessage}/>; if (tab === "logs") return <LogsTab project={project}/>; if (tab !== "versions") return <section className="ptab-panel"><div className="card"><h3 className="card-title">{projectTabs.find(([id]) => id === tab)?.[1]}</h3><p className="hint">迁移中：该模块将按现有 HTML 交互逐项接管。</p></div></section>; return <VersionsTab project={project} versions={versions} onMessage={onMessage} reload={reloadVersions}/> }

function VersionsTab({ project, versions, onMessage, reload }: { project: Project; versions: Version[]; onMessage: (value: string) => void; reload: () => Promise<void> }) { const latest = useMemo(() => versions.find((version) => version.status === "published"), [versions]); const [name, setName] = useState(""); async function create() { const version = await api<Version>(`/projects/${project.id}/versions`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name }) }); setName(""); onMessage(`已创建版本 ${version.version}`); await reload(); } return <section className="ptab-panel"><div className="split-versions"><div className="card version-sidebar"><div className="toolbar compact"><input className="input" value={name} onChange={(event) => setName(event.target.value)} placeholder="1.0.0" data-testid="new-version-input"/><button className="btn btn-primary btn-sm" onClick={create} data-testid="add-version">新建</button></div><ul className="version-list" data-testid="version-list">{versions.map((version) => <li className={`version-item ${version.version === latest?.version ? "latest-published" : ""}`} key={version.id}><span>{version.version} {version.version === latest?.version && <span className="latest-version-label">最新</span>}</span><span className="version-status">{version.status}</span></li>)}</ul></div><div className="card version-detail" data-testid="version-detail"><h3 className="card-title">版本管理</h3><p className="hint">选择版本即可管理包、预览与发布。</p></div></div></section> }

function PushTab({ project, versions, onMessage }: { project: Project; versions: Version[]; onMessage: (value: string) => void }) { const latest = versions.find((version) => version.status === "published"); const [version, setVersion] = useState(""); const [serverIDs, setServerIDs] = useState(""); const [tags, setTags] = useState("test"); const [match, setMatch] = useState("all"); async function deploy(dryRun: boolean) { await api(`/projects/${project.id}/push-deployments`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ version, server_ids: values(serverIDs), tags: values(tags), tag_match: match, dry_run: dryRun }) }); onMessage(dryRun ? "目标筛选完成" : "远程发布任务已排队"); } return <section className="ptab-panel"><div className="card"><div className="card-title-row"><div><h3 className="card-title">发布到远程</h3><p className="hint">默认发布最新已发布版本，支持 server_id、标签及组合筛选。</p></div><span className="badge badge-ok">最新已发布版本：{latest?.version ?? "—"}</span></div><div className="toolbar wrap"><select className="input" value={version} onChange={(event) => setVersion(event.target.value)}><option value="">最新已发布版本</option>{versions.filter((item) => item.status === "published").map((item) => <option value={item.version} key={item.id}>{item.version}</option>)}</select><input className="input" value={serverIDs} onChange={(event) => setServerIDs(event.target.value)} placeholder="服务器 ID，逗号分隔"/><input className="input" value={tags} onChange={(event) => setTags(event.target.value)} placeholder="标签，默认 test"/><select className="input" value={match} onChange={(event) => setMatch(event.target.value)}><option value="all">标签同时满足</option><option value="any">任一标签匹配</option></select><button className="btn btn-secondary btn-sm" onClick={() => deploy(true)}>预演筛选</button><button className="btn btn-primary btn-sm" onClick={() => deploy(false)}>发布到远程</button></div></div></section> }

function LogsTab({ project }: { project: Project }) { const [logs, setLogs] = useState<PushDeployment[]>([]); const load = async () => setLogs((await api<PushDeployment[] | null>(`/projects/${project.id}/push-deployments`)) ?? []); useEffect(() => { void load(); }, [project.id]); return <section className="ptab-panel"><div className="card"><div className="card-title-row"><h3 className="card-title">发布日志</h3><button className="btn btn-secondary btn-sm" onClick={() => void load()}>刷新</button></div><table className="data-table"><thead><tr><th>时间</th><th>版本</th><th>状态</th><th>目标</th></tr></thead><tbody>{logs.map((log) => <tr key={log.id}><td>{log.created_at}</td><td>{log.version}</td><td>{log.status}</td><td>{log.targets?.length ?? 0}</td></tr>)}</tbody></table></div></section> }

createRoot(document.getElementById("root")!).render(<App/>);
